export const FROZEN_CONTROLLED_REQUIREMENTS = [
  {
    key: 'quantity_exact',
    label: 'Exact order quantity',
    description: 'Produce exactly 200 cups.',
    type: 'hard',
    operator: 'equals',
    targetValue: 200,
    unit: 'cups',
    weight: 0,
    displayOrder: 0,
  },
  {
    key: 'moq_max',
    label: 'Maximum MOQ',
    description: "The maker's maximum minimum-order quantity must not exceed 250 units.",
    type: 'hard',
    operator: 'lte',
    targetValue: 250,
    unit: 'units',
    weight: 0,
    displayOrder: 1,
  },
  {
    key: 'capacity',
    label: 'Cup capacity',
    description: 'Each cup should have an approximate capacity of 8 ounces.',
    type: 'hard',
    operator: 'equals',
    targetValue: 8,
    unit: 'ounces',
    weight: 0,
    displayOrder: 2,
  },
  {
    key: 'custom_logo',
    label: 'Logo customization',
    description: 'The maker must support the Harbour Coffee Lab custom cafe logo.',
    type: 'hard',
    operator: 'stated',
    targetValue: true,
    unit: null,
    weight: 0,
    displayOrder: 3,
  },
  {
    key: 'production_time',
    label: 'Maximum production time',
    description: 'Production must take no more than 42 calendar days.',
    type: 'hard',
    operator: 'lte',
    targetValue: 42,
    unit: 'calendar days',
    weight: 0,
    displayOrder: 4,
  },
  {
    key: 'food_contact_documentation',
    label: 'Glaze and food-contact documentation',
    description: 'The maker must state what glaze or food-contact documentation can be supplied.',
    type: 'hard',
    operator: 'stated',
    targetValue: true,
    unit: null,
    weight: 0,
    displayOrder: 5,
  },
  {
    key: 'preproduction_sample',
    label: 'Pre-production sample',
    description: 'A pre-production sample is required before the production order.',
    type: 'hard',
    operator: 'stated',
    targetValue: true,
    unit: null,
    weight: 0,
    displayOrder: 6,
  },
  {
    key: 'communication_language',
    label: 'Communication language',
    description: 'The maker must communicate in English or French.',
    type: 'hard',
    operator: 'one_of',
    targetValue: 'English or French',
    unit: null,
    weight: 0,
    displayOrder: 7,
  },
  {
    key: 'export_history',
    label: 'Previous export experience',
    description: 'The maker must explain whether it has exported previously.',
    type: 'hard',
    operator: 'stated',
    targetValue: true,
    unit: null,
    weight: 0,
    displayOrder: 8,
  },
  {
    key: 'production_style',
    label: 'Handmade or small-batch production',
    description: 'Prefer handmade or small-batch production.',
    type: 'soft',
    operator: 'one_of',
    targetValue: 'handmade or small-batch',
    unit: null,
    weight: 5,
    displayOrder: 9,
  },
  {
    key: 'base_finish',
    label: 'Base finish',
    description: 'Prefer a matte sand or off-white base.',
    type: 'soft',
    operator: 'one_of',
    targetValue: 'matte sand or off-white',
    unit: null,
    weight: 4,
    displayOrder: 10,
  },
  {
    key: 'accent_color',
    label: 'Detailing color',
    description: 'Prefer dark green or ink-blue detailing.',
    type: 'soft',
    operator: 'one_of',
    targetValue: 'dark green or ink-blue',
    unit: null,
    weight: 4,
    displayOrder: 11,
  },
  {
    key: 'artisanal_variation',
    label: 'Visible artisanal variation',
    description: 'Prefer visible variation characteristic of artisanal production.',
    type: 'soft',
    operator: 'equals',
    targetValue: true,
    unit: null,
    weight: 3,
    displayOrder: 12,
  },
  {
    key: 'international_packaging',
    label: 'International-transport packaging',
    description: 'Prefer packaging suitable for international transport.',
    type: 'soft',
    operator: 'equals',
    targetValue: true,
    unit: null,
    weight: 4,
    displayOrder: 13,
  },
  {
    key: 'moroccan_production_centre',
    label: 'Workshop location',
    description:
      'Prefer a workshop in Fez, Safi, Marrakech, or another Moroccan production centre.',
    type: 'soft',
    operator: 'includes',
    targetValue: 'Morocco',
    unit: null,
    weight: 3,
    displayOrder: 14,
  },
  {
    key: 'moq_preferred',
    label: 'Preferred MOQ',
    description: 'Prefer an MOQ below 200 units.',
    type: 'soft',
    operator: 'lte',
    targetValue: 199,
    unit: 'units',
    weight: 3,
    displayOrder: 15,
  },
  {
    key: 'production_time_preferred',
    label: 'Preferred production time',
    description: 'Prefer production below 35 calendar days.',
    type: 'soft',
    operator: 'lte',
    targetValue: 34,
    unit: 'calendar days',
    weight: 3,
    displayOrder: 16,
  },
] as const;
